// <auto-generated />
using System;
using CardVault.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardVault.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CardVaultDbContext))]
    partial class CardVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Accounting.AccountingMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreditAccountCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DebitAccountCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "ProductCode", "EffectiveDate");

                    b.ToTable("AccountingMappings", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Accounting.JournalEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDate");

                    b.HasIndex("SourceModule", "SourceReference", "EventType")
                        .IsUnique();

                    b.ToTable("JournalEntries", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Accounting.JournalEntryLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.HasIndex("LedgerAccountId");

                    b.ToTable("JournalEntryLines", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Accounting.LedgerAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.ToTable("LedgerAccounts", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Audit.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredOn");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.AmortizationScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BilledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("BilledStatementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("PaidOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalInstallmentAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "InstallmentNumber")
                        .IsUnique();

                    b.HasIndex("Status", "DueDate");

                    b.ToTable("AmortizationSchedules", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.AuthorizationHoldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("AuthorizedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CaptureLedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapturedAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("CapturedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HoldLedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("MerchantCategory")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("MerchantId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OriginalDataElements90")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ReleasedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rrn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Stan")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuthorizationHolds");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.CreditPolicyEntity", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("AllowOverlimit")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AnnualFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AutoIncreaseMinOnTimeRatio")
                        .HasColumnType("numeric");

                    b.Property<int>("AutoIncreaseMinStatements")
                        .HasColumnType("integer");

                    b.Property<decimal>("AutoIncreaseMinUtilization")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AutoIncreasePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CashAdvanceApr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CashAdvanceFeeFixed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CashAdvanceFeePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FloorLimit")
                        .HasColumnType("numeric");

                    b.Property<int>("GraceDays")
                        .HasColumnType("integer");

                    b.Property<int>("HoldTtlHours")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestApr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LateFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinPaymentAbsolute")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinPaymentPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OverlimitBufferAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OverlimitFee")
                        .HasColumnType("numeric");

                    b.Property<bool>("OverlimitFeeOncePerDay")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PenaltyApr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PurchaseApr")
                        .HasColumnType("numeric");

                    b.Property<int>("PurchaseGraceDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductCode");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("CreditPolicies", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.DelinquencyRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Bucket")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysInArrears")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverdueAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("ResolvedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StatementId");

                    b.HasIndex("AccountId", "Status");

                    b.ToTable("DelinquencyRecords", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.DisputeCaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("OpenedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("OriginalTxnJournalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProvisionalCreditLedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ResolvedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rrn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Stan")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Network", "Rrn");

                    b.ToTable("DisputeCases", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.FeeAssessmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "FeeType", "BusinessDate")
                        .IsUnique();

                    b.ToTable("FeeAssessments", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.InstallmentPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InterestApr")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("OriginalLedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("RemainingInstallments")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalInstallments")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("InstallmentPlans", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.InterestAccrualRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AccrualDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Apr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalanceBase")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Segment")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "AccrualDate", "Segment")
                        .IsUnique();

                    b.ToTable("InterestAccrualRecords", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.LedgerEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("PostedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StatementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatementId");

                    b.HasIndex("AccountId", "PostedOn");

                    b.ToTable("LedgerEntries", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.MccRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Mcc")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal?>("PerTxnLimit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Mcc")
                        .IsUnique();

                    b.ToTable("MccRules", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.MinimumPaymentPolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CeilingAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FloorAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IncludeFees")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeInterest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrincipalPercent")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MinimumPaymentPolicies", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.PaymentAllocationPolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PaymentAllocationPolicies", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.StatementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageDailyBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CycleEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CycleStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FeesDue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Interest")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InterestAccrued")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InterestApr")
                        .HasColumnType("numeric");

                    b.Property<int>("InterestDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestDue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LateFeeAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("LateFeeAppliedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinimumPayment")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaidToFees")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaidToInterest")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaidToPrincipal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Payments")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PreviousBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrincipalDue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Purchases")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StatementBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPaymentDue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "StatementDate");

                    b.ToTable("Statements", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.StatementLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PostedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LedgerEntryId");

                    b.HasIndex("StatementId", "PostedOn");

                    b.ToTable("StatementLines", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.VelocityRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("WindowMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.ToTable("VelocityRules", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Catalog.BinRangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BinEnd")
                        .HasColumnType("integer");

                    b.Property<int>("BinStart")
                        .HasColumnType("integer");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("IssuerName")
                        .HasColumnType("text");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("BinStart", "BinEnd");

                    b.ToTable("BinRanges", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Catalog.CardProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CardProducts", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Catalog.CountryEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NumericCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Code");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.CreditLimits.CreditLimitProposalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppliedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("AverageUtilizationRatio")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OnTimePaymentRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProposedIncreaseAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProposedLimit")
                        .HasColumnType("numeric");

                    b.Property<int>("StatementsReviewed")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Status", "CreatedOn");

                    b.ToTable("CreditLimitProposals", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.CreditLimits.OverlimitEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ApprovedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AvailableCreditBefore")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HoldId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OverlimitAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("HoldId")
                        .IsUnique();

                    b.HasIndex("AccountId", "CreatedOn");

                    b.ToTable("OverlimitEvents", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Ecommerce.ThreeDsChallengeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("AuthenticatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BrowserIpCountry")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContactHint")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceChannel")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("ExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("MerchantCountry")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OtpAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OtpSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RiskReasonsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TraceId");

                    b.HasIndex("CardId", "CreatedOn");

                    b.HasIndex("Status", "CreatedOn");

                    b.ToTable("ThreeDsChallenges", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.AccountLimitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DailyAtmAuculated")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyAtmLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyEcommerceAccumulated")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyEcommerceLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyPosAccumulated")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyPosLimit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AccountLimits", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CardAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<decimal>("AvailableLimit")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HoldBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LedgerBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "AccountType");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpiryYyMm")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<string>("PanToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("PinBlockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PinHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PinRetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Last4");

                    b.HasIndex("PanToken")
                        .IsUnique();

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CardStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ChangedOn");

                    b.ToTable("CardStatusHistory", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CardDeliveryCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ResidenceCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatementAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StatementCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Loyalty.LoyaltyBalanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashbackBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PointsBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("LoyaltyBalances", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Loyalty.LoyaltyEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashbackAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer");

                    b.Property<Guid>("LoyaltyBalanceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PointsAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyBalanceId");

                    b.HasIndex("AccountId", "CreatedOn");

                    b.HasIndex("AccountId", "SourceType", "SourceReference", "EntryType")
                        .IsUnique();

                    b.ToTable("LoyaltyEntries", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Loyalty.RewardCatalogItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashbackCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("PointsCost")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RewardCatalogItems", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Loyalty.RewardProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashbackRate")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PointsPerCurrencyUnit")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode", "EffectiveDate");

                    b.ToTable("RewardPrograms", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Notifications.CustomerNotificationDeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DestinationMasked")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("LastAttemptOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId", "Channel")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedOn");

                    b.ToTable("CustomerNotificationDeliveries", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Notifications.CustomerNotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ReadOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("SourceEvent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "CreatedOn");

                    b.HasIndex("Type", "CreatedOn");

                    b.ToTable("CustomerNotifications", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.OpenBanking.OpenBankingClientAccountAccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ClientEntityId", "AccountId")
                        .IsUnique();

                    b.ToTable("OpenBankingClientAccountAccesses", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.OpenBanking.OpenBankingClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAllAccounts")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedScopes")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastTokenIssuedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenBankingClients", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Outbox.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Routing.RoutingRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AmountMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AmountMin")
                        .HasColumnType("numeric");

                    b.Property<int>("BinEnd")
                        .HasColumnType("integer");

                    b.Property<int>("BinStart")
                        .HasColumnType("integer");

                    b.Property<string>("ConnectorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Mcc")
                        .HasColumnType("text");

                    b.Property<string>("MerchantId")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Priority");

                    b.HasIndex("BinStart", "BinEnd");

                    b.ToTable("RoutingRules", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Settlement.SettlementBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Network")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TxnCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Network", "BusinessDate")
                        .IsUnique();

                    b.ToTable("SettlementBatches", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Settlement.SettlementItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("NetworkRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("PostedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "PostedOn");

                    b.ToTable("SettlementItems", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Switch.AntifraudRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("numeric");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AntifraudRules");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Switch.DisputeEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DisputeId", "CreatedOn");

                    b.ToTable("DisputeEvents", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Switch.RefundRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("PostedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rrn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Stan")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Network", "Rrn", "Stan")
                        .IsUnique();

                    b.ToTable("RefundRecords", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Switch.TxnJournalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mti")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("PostedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rrn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Stan")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TxnType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Network", "Mti", "Stan", "Rrn")
                        .IsUnique();

                    b.ToTable("TxnJournal", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Vault.TokenVaultEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("CiphertextB64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastAccessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaskedPan")
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)");

                    b.Property<string>("NonceB64")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TagB64")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("MaskedPan");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("TokenVault", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Vault.VaultSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveKeyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastReencryptRunOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastReencryptStatus")
                        .HasColumnType("text");

                    b.Property<int>("LastReencryptUpdated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VaultSettings", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Wallets.WalletAuthorizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("AuthorizedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientTransactionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("DeviceAuthenticated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("HoldId")
                        .HasColumnType("uuid");

                    b.Property<string>("MerchantCategory")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("MerchantId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TokenReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("WalletTokenId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientTransactionId")
                        .IsUnique();

                    b.HasIndex("WalletTokenId");

                    b.HasIndex("AccountId", "AuthorizedOn");

                    b.ToTable("WalletAuthorizations", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Wallets.WalletTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivationCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ActivationExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivationHint")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("LastUsedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TokenReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WalletReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("TokenReference")
                        .IsUnique();

                    b.HasIndex("CardId", "Provider", "DeviceReference");

                    b.ToTable("WalletTokens", (string)null);
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Accounting.JournalEntryLineEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Accounting.JournalEntryEntity", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardVault.Infrastructure.Persistence.Accounting.LedgerAccountEntity", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");

                    b.Navigation("LedgerAccount");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.AmortizationScheduleEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Billing.InstallmentPlanEntity", null)
                        .WithMany("AmortizationSchedule")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.LedgerEntryEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Billing.StatementEntity", "Statement")
                        .WithMany()
                        .HasForeignKey("StatementId");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.StatementLineEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Billing.LedgerEntryEntity", "LedgerEntry")
                        .WithMany()
                        .HasForeignKey("LedgerEntryId");

                    b.HasOne("CardVault.Infrastructure.Persistence.Billing.StatementEntity", "Statement")
                        .WithMany("Lines")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LedgerEntry");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Ecommerce.ThreeDsChallengeEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Issuer.CardEntity", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CardAccountEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Issuer.CustomerEntity", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CardEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Issuer.CardAccountEntity", "Account")
                        .WithMany("Cards")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CardStatusHistoryEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Issuer.CardEntity", "Card")
                        .WithMany("History")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Loyalty.LoyaltyEntryEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Loyalty.LoyaltyBalanceEntity", "LoyaltyBalance")
                        .WithMany("Entries")
                        .HasForeignKey("LoyaltyBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoyaltyBalance");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Notifications.CustomerNotificationDeliveryEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Notifications.CustomerNotificationEntity", "Notification")
                        .WithMany("Deliveries")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Notifications.CustomerNotificationEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Issuer.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.OpenBanking.OpenBankingClientAccountAccessEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.OpenBanking.OpenBankingClientEntity", "Client")
                        .WithMany("AccountAccesses")
                        .HasForeignKey("ClientEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Settlement.SettlementItemEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Settlement.SettlementBatchEntity", "Batch")
                        .WithMany("Items")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Wallets.WalletAuthorizationEntity", b =>
                {
                    b.HasOne("CardVault.Infrastructure.Persistence.Wallets.WalletTokenEntity", "WalletToken")
                        .WithMany("Authorizations")
                        .HasForeignKey("WalletTokenId");

                    b.Navigation("WalletToken");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Accounting.JournalEntryEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.InstallmentPlanEntity", b =>
                {
                    b.Navigation("AmortizationSchedule");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Billing.StatementEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CardAccountEntity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CardEntity", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Issuer.CustomerEntity", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Loyalty.LoyaltyBalanceEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Notifications.CustomerNotificationEntity", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.OpenBanking.OpenBankingClientEntity", b =>
                {
                    b.Navigation("AccountAccesses");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Settlement.SettlementBatchEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CardVault.Infrastructure.Persistence.Wallets.WalletTokenEntity", b =>
                {
                    b.Navigation("Authorizations");
                });
#pragma warning restore 612, 618
        }
    }
}
